apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: papertoprod-api
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount | default 2 }}
  strategy:
    blueGreen:
      activeService: papertoprod-api-active
      previewService: papertoprod-api-preview
      autoPromotionEnabled: false
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: papertoprod-api
  template:
    metadata:
      labels:
        app: papertoprod-api
    spec:
      containers:
      - name: api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8000
        env:
        - name: DEPLOYMENT_VERSION
          value: "{{ .Values.image.tag }}"
        {{- if .Values.externalDatabase }}
        - name: DATABASE_URL
          value: "{{ .Values.externalDatabase.url }}"
        {{- end }}
        {{- if .Values.externalRedis }}
        - name: REDIS_URL
          value: "{{ .Values.externalRedis.url }}"
        {{- end }}
        {{- if .Values.externalS3 }}
        - name: S3_ENDPOINT_URL
          value: "{{ .Values.externalS3.endpoint }}"
        - name: AWS_ACCESS_KEY_ID
          value: "{{ .Values.externalS3.accessKey }}"
        - name: AWS_SECRET_ACCESS_KEY
          value: "{{ .Values.externalS3.secretKey }}"
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
